name: Publish to edge

on:
  workflow_dispatch:
  push:

jobs:
  publish-to-edge:
    uses: canonical/operator-workflows/.github/workflows/publish_charm.yaml@webhook-router-fix-publish-wf
    secrets: inherit
    with:
      channel: latest/edge
      charm-directory: charm
      charmcraft-channel: "latest/edge"
